### ISSUE TITLE
Create initial Frontend for Backend Student

### ISSUE THREAD

**Issue by PJUllrich** [Quintor/StudyBits#25]
Using Angular

**Comment by pimotte** [comment]
Do we want to have a seperate repo for the frontend? I'm getting admin rights to the Quintor org this afternoon, so I could create it then.

**Comment by PJUllrich** [comment]
I thought about putting it into the students project as a frontend package since it also requires some it also uses spring. but I'm indifferent about this. It's easier to just put it in there, but I could also create a separate project. Whatever you prefer.

**Comment by pimotte** [comment]
What stack/technology are you intending to use? If we're serving it from the backend, then I have no issues with putting it in this repo

**Comment by PJUllrich** [comment]
Backend uses Spring to serve a REST framework.
Frontend uses Angular 4(?) and is served using Spring as well. 

So, given that I use Spring for both, I think we can simply put it into the same repository.

**Comment by pimotte** [comment]
Is there a particular reason you want to serve the frontend using spring? If we're using Angular, (with angular-cli?) , a simple `ng serve` gets us a webserver, and building a distributable for inclusion in the backend seems like more work as opposed to adding another docker container to run a node server. 

I'm not particularly opposed to serving from Spring, but above is the path I have taken in the past.

**Comment by PJUllrich** [comment]
No particular reason except for that we're already using it. I will follow your recommendation and put the frontend into separate folder for now until we can create a separate repository.

**Comment by PJUllrich** [comment]
Progress Report:
![image](https://user-images.githubusercontent.com/10426523/37521606-9123461c-2921-11e8-8048-f94b5ee8e677.png)
