### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by pimotte** [Quintor/StudyBits#73]
- [x] Add (snackbar) notification on successful proof 
- [x] Show the names of attributes on a proof request.
- [ ] Extend UserProof to include degree-specific information
- [x] Show the values of attributes on a proof request
- [x] Use nice sample data (student1 -> Lisa)
- [x] Don't show json in interface (but format nicely)
- [x] "Nothing to see here" row if table is empty
- [x] Quintor logo in frontend

**Comment by pimotte** [comment]
Working on the proof notification

**Comment by PJUllrich** [comment]
I implemented the attribute names already
