### ISSUE TITLE
Refactor Onboarding functionality in Wrapper

### ISSUE THREAD

**Issue by PJUllrich** [Quintor/StudyBits#95]
We have onboarding functions in 2 different classes.
`createConnectionRequest` and `acceptConnectionResponse` are in `TrustAnchor`
`acceptConnectionRequest` is in `WalletOwner`

In the University backend code, the `createConnectionRequest` and `acceptConnectionResponse` functions are called via the `Issuer` class, which is a child class of `TrustAnchor`.
In the Student backend, the `acceptConnectionRequest` is called via the `Prover` class, which is a child class of `WalletOwner`.

Should we maybe streamline the functions and the calls so that it becomes more clear where to find the onboarding functionality? Since `TrustAnchor` inherits form `WalletOwner`, maybe we can give the onboarding functionality to `WalletOwner`?

**Comment by pimotte** [comment]
The point of this is that in the way we've currently set it up, all DIDs go to the ledger, which means that a trustanchor needs to write them.

**Comment by pimotte** [comment]
Was refactored.
