### ISSUE TITLE
Streamline attributes in createCredential and fulfillProofRequest

### ISSUE THREAD

**Issue by PJUllrich** [Quintor/StudyBits#97]
The function `createCredential` in `Issuer` has a `Map<String, Object>` as second parameter.
The function `fulfillProofRequest` in `Prover` has a `Map<String, String>` as parameter.

In the `Main` function, this causes me some issue with handing in the attributes into `fulfillProofRequest` that I've used previously to create the Claim. Do you think that these two should maybe be made equal to e.g. `Map<String, Object>`?

**Comment by PJUllrich** [comment]
Not feasible since the wrapper functions need the Maps as input parameters.

**Comment by pimotte** [comment]
I'd say we want this, but we actually need to refactor the wrapper to support both datatypes, currently the proving supports only Strings for a reason I forgot.  So I'll reopen this and mark this as "wrapper"

**Comment by pimotte** [comment]
Moved to https://github.com/Quintor/quindy/issues/30
